MOVE_TURN_TEXT:
  NEXT_TURN: Ходят
  WON: Победили
  DRAW: Ничья
MOVE_TURN_TEXT_ONLINE:
  NEXT_TURN: Ходит {}
  WON: Победил игрок {}
  DRAW: Ничья
NO_SESSION_TEXT:
  INFORM_MESSAGE: | 
    Похоже, что игра закончена или время сессии истекло :(
    Вы можете начать новую игру:
    /single_game - игра на одном устройстве
    /online_game - пригласить игрока, с которым уже играл ранее
INVITE_EVENT_TEXT:
  INVITE_MESSAGE: |
    Привет! {} бросает тебе вызов в крестики-нолики
  CHOOSE_USER_MESSAGE: |
    Выбери соперника из списка ниже
    или пригласи нового: /invite_new_user
  NO_LINKED_USERS_YET: |
    У тебя еще нет связанного списка игроков
    Чтобы пригласить нового пользователя воспользуся командой /invite_new_user
  AGREE: Начнем!
  DISAGREE: Не сейчас :(
  INVITE_WAS_SENT_SUCCESSFULLY: |
    Приглашение для {} успешно отправлено
    Ожидаем ответа
  INVITE_WAS_SENT_UNSUCCESSFULLY: |
    Не удалось отправить приглашение для {}
    Похоже, что этот игрок заблокировал бота
    Попросите его разблокировать бота или пригласите другого игрока
INVITE_ANSWER_TEXT:
  INVITED_USER_DISAGREE: Значит в следующий раз
  INVITED_USER_AGREE: Отлично!
  INITIATOR_USER_DISAGREE: |
    {} не хочет сейчас играть :(
  INITIATOR_USER_AGREE: |
    {} согласился!
INVITING_BY_ID:
  INFO: |
    Ваш USER ID: {}
  UNKOWN_USER: |
    Данный пользователь еще не известен для бота. Пожалуйста, попросите его начать диалог с ботом и повторите попытку
    Ссылка на бота: https://t.me/andkor_test_bot
  GIVE_ME_USER_ID: |
    Ответным сообщением напишите ID пользователя, которого хотите пригласить
    Если не знаете ID, то пожалуйста, попросите этого пользователя начать диалог с ботом
    Ссылка на бота: https://t.me/andkor_test_bot
    Узнать свой ID: /my_id
  INVITING_HIMSELF: Нельзя приглашать самого себя
INTRODUCING:
  MESSAGE: |
    Это простой бот для игры в крестики-нолики с твоими друзьями
    Можешь играть как на одном устройстве, так и онлайн: приглашай своих друзей /online_game
    Бот запомнит игроков, с которыми ты сыграл и сохранит в удобном списке для повторных вызовов
    Список команд можешь найти в меню
